jest.autoMockOff();
/*jest.dontMock('../index');
jest.dontMock('lodash');
jest.dontMock('../config/settings.js');
jest.dontMock('../lib/mediator');
jest.dontMock('../lib/scopes');
jest.dontMock('../lib/services');
jest.dontMock('../lib/events');
jest.dontMock('../lib/module-api-constructor.js');
jest.dontMock('../lib/module-public-api-constructor.js');
jest.dontMock('../lib/proxy-event-constructor.js');*/
